### ISSUE TITLE
Request to have a demo site for this lib

### ISSUE THREAD

**Issue by beanbocchi** [1cheese/pixi-fps-counter#4]
My call to this lib:
![image](https://github.com/1cheese/pixi-fps-counter/assets/46867018/009984cb-79b1-48db-a4f9-c93672e4f7c3)
But see nothing when run, I dont understand what will this lib render

**Comment by 1cheese** [comment]
@khoakomlem, you should add the counter to your app stage to make it visible. Like this:
```
worldClient.app.stage.addChild(this.counter);
```
I'm going to add this information to the docs. Not sure if I'll be able to create a demo site in nearest future.

**Comment by beanbocchi** [comment]
> @khoakomlem, you should add the counter to your app stage to make it visible. Like this:
> 
> ```
> worldClient.app.stage.addChild(this.counter);
> ```
> 
> I'm going to add this information to the docs. Not sure if I'll be able to create a demo site in nearest future.

Worked haha
